version: '3'
services:
  whatsapp_crm:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - EVOLUTION_API_URL=http://host.docker.internal:8080
      - EVOLUTION_API_KEY=sua-chave-da-api
      - SECRET_KEY=chave-secreta-para-sessoes
    extra_hosts:
      - "host.docker.internal:host-gateway"
