version: '3'

services:
  whatsapp_crm:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - EVOLUTION_API_URL=http://host.docker.internal:8080
      - EVOLUTION_API_KEY=XarFms2vtu6zfD19UYsRs4VCto0YbeYV
      - SECRET_KEY=jakomp123467
    extra_hosts:
      - "host.docker.internal:host-gateway"